"""
Centralized warning/blocker/risk flag codes for Tool 1 outputs.
"""

WARNING_CODES = {
    'MULTI_API_PRODUCT',
    'PLAN_SPLIT_REQUIRED',
    'REVIEW_REQUIRED',
    'SHAREDFLOW_REFERENCE',
    'MANUAL_SHARED_POLICY_GROUP_MAPPING_REQUIRED',
    'CONDITIONAL_SHAREDFLOW_REFERENCE',
    'MULTIPLE_SHAREDFLOW_INVOCATIONS',
    'TARGETSERVER_REFERENCE',
    'CONDITIONAL_TARGETSERVER_REFERENCE',
    'MULTIPLE_TARGETSERVER_REFERENCES',
    'INCOMPLETE_TARGETSERVER_CONFIGURATION',
    'KVM_WRITE_OPERATION',
    'SEMANTIC_SHIFT_REVIEW_REQUIRED',
    'OWNED_BY_INACTIVE_DEVELOPER',
    'CREDENTIAL_OF_INACTIVE_DEVELOPER',
}

BLOCKER_CODES = {
    'MISSING_REFERENCED_PROXY',
    'MISSING_REFERENCED_SHAREDFLOW',
    'MISSING_REFERENCED_TARGETSERVER',
    'MALFORMED_ARTIFACT',
    'UNREADABLE_ARTIFACT',
    'DUPLICATE_IDENTITY_COLLISION',
}

RISK_FLAG_CODES = {
    'API_KEY_CONTINUITY_RISK',
    'OAUTH_CLIENT_CONTINUITY_RISK',
    'INACTIVE_DEVELOPER',
    'MULTI_PRODUCT_CREDENTIAL',
    'POSSIBLE_SENSITIVE',
    'HIGH_CARDINALITY',
    'EMPTY_ONLY',
}
